version: '2.1'

services:

  wb-backend:
    image: wb.image
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - ./:/wake.booking
    environment:
      DB_USERNAME: root
      DB_NAME: wake_booking
      DB_HOST: mysqldb
      DB_PORT: 3306
      NODE_ENV: "development"
    depends_on:
      - mysqldb
    entrypoint: ["npm", "run", "debug"]

  mysqldb:
    image: mysql:5.7
    ports:
      - "3308:3308"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"