FROM node:carbon
MAINTAINER Eugene Krotenko <ekrotenko.ua@gmail.com>

ADD ./ /wake.booking
WORKDIR /wake.booking

RUN npm install -g -q nodemon sequelize-cli

CMD npm install -q --no-progress && \
    npm start
